---
title: "simpleBayesSimpleSim"
author: "Kristian Severin"
date: "2023-05-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# loading packages
pacman::p_load(  
  tidyverse,
  brms,
  cmdstanr,
  patchwork,
  future, 
  purrr, 
  furrr,
  bayesplot,
  drc
  )

source("SimpleBayes_f.R")  # get self-written simplebayes function from source
source("priorSens_f.R")  # get self-written function for prior sensitivity analysis
```

```{r}
nskiers <- 10
bias <- seq(0.1,0.9, 0.1)
trials <- seq(10)
Source1 <- seq(0.1,0.9, 0.1)
Source2 <- seq(0.1,0.9, 0.1)


dbS <- expand.grid(bias = bias, trials, Source1 = Source1, Source2 = Source2)

for (n in seq(nrow(dbS))) {
  dbS$beliefAssessment[n] <- SimpleBayes_f(dbS$bias[n], dbS$Source1[n], dbS$Source2[n])
 
  dbS$outcome[n] <- rbinom(1,1, db$beliefAssessment[n])
 
  dbS$continuous[n] <- db$beliefAssessment[n] * 11
 
  dbS$discrete[n] <- round(db$beliefAssessment[n] * 11,0)
 
}

dbS <- rename(dbS, "skier" = "Var2") 

#db <- sample_n(db, size = 26244)

#db <- db %>% na.omit()
```


```{r}
# pivot data wider
sim_wide_simpleS<- dbS %>% 
  group_by(skier) %>% 
  subset(select = c(skier, outcome, Source1, Source2, bias)) %>%
  mutate(row = row_number()) %>% 
  pivot_wider(names_from = skier, values_from = c(outcome, Source1, Source2, bias))

sim_wide_simpleS <- sim_wide_simpleS %>% na.omit()

# Create the data
dataSimpleBayesS <- list(
  N = nrow(sim_wide_simpleS),
  S = nskiers,
  outcome = as.matrix(sim_wide_simpleS[,2:11]),
  Source1 = as.matrix(sim_wide_simpleS[,12:21]),
  Source2 = as.matrix(sim_wide_simpleS[,22:31]),
  bias = as.matrix(sim_wide_simpleS[,32:41])
)

# feed R the stan model
file <- file.path("simplebayesML.stan")
mod_SimpleBayesS <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
# create samples from the model
samples_simpleS <- mod_SimpleBayesS$sample(
  data = dataSimpleBayesS,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500,
  max_treedepth = 10
)

# get the resulting data frame
draws_df_simpleS <- as_draws_df(samples_simpleS$draws())
```

This chunk has the prior and posterior predictive checks for the bias parameter
```{r}
Prior_predictive_checks_p <- 
ggplot(draws_df_simpleS) +
  geom_histogram(aes(`prior_preds5[1]`), color = "yellow", fill = "lightyellow", alpha = 0.2) +
    annotate("text",  x = 340, y = 2100, label = "*0.5-Adjusted Prior" , hjust = 0)+
  geom_histogram(aes(`prior_preds7[1]`), color = "green", fill = "lightgreen", alpha = 0.2) +
    annotate("text",  x = 450, y = 900, label = "*0.7-Adjusted Prior" , hjust = 0)+
  geom_histogram(aes(`prior_preds9[1]`), color = "blue", fill = "lightblue", alpha = 0.2) +
    annotate("text",  x = 550, y = 600, label = "*0.9-Adjusted Prior" , hjust = 0)+
  xlab("Predicted skied runs out of 729") +
  ylab("Posterior Density") +
  ggtitle("Prior Predictive Checks")+
  theme_classic()

both_bs5 <- ggplot(draws_df_simpleS) +
  geom_histogram(aes(`prior_preds5[1]`), color = "lightyellow", fill = "yellow", alpha = 0.3, bins = 90) +
  geom_histogram(aes(`post_preds5[1]`), color = "#666600", fill = "yellow", alpha = 0.3, bins = 90) +
  xlab("Predicted skied runs out of 729 trials") +
  ylab("Posterior Density") +
  ggtitle("β 0.5 adjusted prior")+
  theme_classic()

both_bs7 <- ggplot(draws_df_simpleS) +
  geom_histogram(aes(`prior_preds7[1]`), color = "lightgreen", fill = "green", alpha = 0.3, bins = 90) +
  geom_histogram(aes(`post_preds7[1]`), color = "darkgreen", fill = "green", alpha = 0.3, bins = 90) +
  xlab("Predicted skied runs out of 729 trials") +
  ylab("Posterior Density") +
  ggtitle("β 0.7 adjusted prior")+
  theme_classic()

both_bs9 <- ggplot(draws_df_simpleS) +
  geom_histogram(aes(`prior_preds9[1]`), color = "lightblue", fill = "blue", alpha = 0.3, bins = 90) +
  geom_histogram(aes(`post_preds9[1]`), color = "darkblue", fill = "blue", alpha = 0.3, bins = 90) +
  xlab("Predicted skied runs out of 729 trials") +
  ylab("Posterior Density") +
  ggtitle("β 0.9 adjusted prior")+
  theme_classic()

Prior_predictive_checks_p

both_bs5+both_bs7+both_bs9 + plot_annotation(title = "Prior and Posterior Predictive Checks", subtitle = "Simple Bayes Model Parameter")
```

```{r}
# adding different priors for bias
prior_mean <- seq(-3, 3, .5)
prior_sd <- seq(0.1, 1, 0.1)
priors <-  expand.grid(prior_mean, prior_sd)
priors <- tibble(prior_mean = priors$Var1, prior_sd = priors$Var2)

# feed R the stan model with priors
file <- file.path("sbPriors.stan")
mod <- cmdstan_model(file, 
                     cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))

# use all cores on the computer
plan(multisession, workers = 4)

# calling function self-written function that simulates data and fits it by sequences of different priors
prior_sens_dfS <- future_pmap_dfr(priors, sim_d_and_fit, .options = furrr_options(seed = TRUE))
```

```{r}
# prior sensitivity
ggplot(prior_sens_dfS, aes(prior_mean, bias_posterior1)) +
  xlab("Prior Mean")+
  ylab("Bias Posterior")+
  geom_point(alpha = 0.1) +
  geom_hline(yintercept = 0.8, color = "red") +
  geom_smooth() +
  facet_wrap(.~prior_sd, labeller = labeller(prior_sd = 
    c("0.1" = "prior standard deviation: 0.1",
      "0.2" = "prior standard deviation: 0.2",
      "0.3" = "prior standard deviation: 0.3",
      "0.4" = "prior standard deviation: 0.4",
      "0.5" = "prior standard deviation: 0.5",
      "0.6" = "prior standard deviation: 0.6",
      "0.7" = "prior standard deviation: 0.7",
      "0.8" = "prior standard deviation: 0.8",
      "0.9" = "prior standard deviation: 0.9",
      "1" = "prior standard deviation: 1"
      )))+
  theme_classic()

ggplot(prior_sens_dfS, aes(prior_mean, bias_posterior2)) +
  geom_point(alpha = 0.1) +
  geom_hline(yintercept = 0.8, color = "red") +
  geom_smooth() +
  facet_wrap(.~prior_sd) +
  theme_classic()
```


This chunk has the prior posterior update plots for the bias parameter
```{r}
# bias plot
b1 <- ggplot(draws_df_simpleS) +
  geom_density(aes(`bias_posterior[1]`), alpha = 0.6, fill = "lightblue") +

  geom_density(aes(`bias_prior[1]`), alpha = 0.6, fill = "pink") +

  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = mean(dbS$bias), linetype = "dashed", size = 1.5) +

  ggtitle("Simulated Skier 1")

# bias plot
b2 <- ggplot(draws_df_simpleS) +
  geom_density(aes(`bias_posterior[2]`), alpha = 0.6, fill = "lightblue") +

  geom_density(aes(`bias_prior[2]`), alpha = 0.6, fill = "pink") +

  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = mean(dbS$bias), linetype = "dashed", size = 1.5) +

  ggtitle("Simulated Skier 2")

# bias plot
b3 <- ggplot(draws_df_simpleS) +
  geom_density(aes(`bias_posterior[3]`), alpha = 0.6, fill = "lightblue") +

  geom_density(aes(`bias_prior[3]`), alpha = 0.6, fill = "pink") +

  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = mean(dbS$bias), linetype = "dashed", size = 1.5) +

  ggtitle("Simulated Skier 3")

# bias plot
b4 <- ggplot(draws_df_simpleS) +
  geom_density(aes(`bias_posterior[4]`), alpha = 0.6, fill = "lightblue") +

  geom_density(aes(`bias_prior[4]`), alpha = 0.6, fill = "pink") +

  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = mean(dbS$bias), linetype = "dashed", size = 1.5) +

  ggtitle("Simulated Skier 4")

# bias plot
b5 <- ggplot(draws_df_simpleS) +
  geom_density(aes(`bias_posterior[5]`), alpha = 0.6, fill = "lightblue") +

  geom_density(aes(`bias_prior[5]`), alpha = 0.6, fill = "pink") +

  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = mean(dbS$bias), linetype = "dashed", size = 1.5) +

  ggtitle("Simulated Skier 5")

# bias plot
b6 <- ggplot(draws_df_simpleS) +
  geom_density(aes(`bias_posterior[6]`), alpha = 0.6, fill = "lightblue") +

  geom_density(aes(`bias_prior[6]`), alpha = 0.6, fill = "pink") +

  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = mean(dbS$bias), linetype = "dashed", size = 1.5) +

  ggtitle("Simulated Skier 6")

# bias plot
b7 <- ggplot(draws_df_simpleS) +
  geom_density(aes(`bias_posterior[7]`), alpha = 0.6, fill = "lightblue") +

  geom_density(aes(`bias_prior[7]`), alpha = 0.6, fill = "pink") +

  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = mean(dbS$bias), linetype = "dashed", size = 1.5) +

  ggtitle("Simulated Skier 7")

# bias plot
b8 <- ggplot(draws_df_simpleS) +
  geom_density(aes(`bias_posterior[8]`), alpha = 0.6, fill = "lightblue") +

  geom_density(aes(`bias_prior[8]`), alpha = 0.6, fill = "pink") +

  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = mean(dbS$bias), linetype = "dashed", size = 1.5) +

  ggtitle("Simulated Skier 8")

# bias plot
b9 <- ggplot(draws_df_simpleS) +
  geom_density(aes(`bias_posterior[9]`), alpha = 0.6, fill = "lightblue") +

  geom_density(aes(`bias_prior[9]`), alpha = 0.6, fill = "pink") +

  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = mean(dbS$bias), linetype = "dashed", size = 1.5) +

  ggtitle("Simulated Skier 9")

# bias plot
b10 <- ggplot(draws_df_simpleS) +
  geom_density(aes(`bias_posterior[10]`), alpha = 0.6, fill = "lightblue") +

  geom_density(aes(`bias_prior[10]`), alpha = 0.6, fill = "pink") +

  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = mean(dbS$bias), linetype = "dashed", size = 1.5) +

  ggtitle("Simulated Skier 10")

pb_all <- b1+b2+b3+b4+b5+b6+b7+b8+b9+b10+plot_annotation(title = "Prior Posterior Update Checks for the Simulated Skiers", 
                                                         theme = theme(plot.title = element_text(size = 20, hjust = 0.5)))

pb_all



```

This chunk has the chains mixing traceplots for the bias parameter
```{r}
# chains mixing plot
mp1S <- ggplot(draws_df_simpleS, aes(.iteration, `bias[1]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
mp2S <- ggplot(draws_df_simpleS, aes(.iteration, `bias[2]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
mp3S <- ggplot(draws_df_simpleS, aes(.iteration, `bias[3]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
mp4S <- ggplot(draws_df_simpleS, aes(.iteration, `bias[4]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
mp5S <- ggplot(draws_df_simpleS, aes(.iteration, `bias[5]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
mp6S <- ggplot(draws_df_simpleS, aes(.iteration, `bias[6]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
mp7S <- ggplot(draws_df_simpleS, aes(.iteration, `bias[7]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
mp8S <- ggplot(draws_df_simpleS, aes(.iteration, `bias[8]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
mp9S <- ggplot(draws_df_simpleS, aes(.iteration, `bias[9]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
mp10S <- ggplot(draws_df_simpleS, aes(.iteration, `bias[10]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

mix_w_allS <- ggarrange(mp1S, mp2S, mp3S, mp4S, mp5S, mp6S, mp7S, mp8S, mp9S, mp10S)

annotate_figure(mix_w_all, top = text_grob("Chains Mixing Plot Simple Bayes Model for the β Parameter", 
                face = "bold", size = 14))

mix_w_allS
```


```{r}
# leave one out cross-validation information criteria
samples_simpleS$loo()
```


```{r}
parameter_recovery_dfb <- NULL  

for (biasLvl in unique(db$bias)){
 
  dataSimpleBayesParam <- db %>% subset(
      bias == biasLvl  
    )
  
  # Create the data
samples_ss <- dataSimpleBayesParam$sample( 
  data = list(
  N = nrow(dataSimpleBayesParam),
  S = 1,
  outcome = as.matrix(dataSimpleBayesParam$outcome),
  Source1 = as.matrix(dataSimpleBayesParam$Source1),
  Source2 = as.matrix(dataSimpleBayesParam$Source2)
),

  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 0,
  max_treedepth = 10,
  adapt_delta = 0.99
      )
   
  draws_df_param_recov_b <- as_draws_df(samples_w$draws()) 
  temp_paramb <- tibble(
                   biasEstScaled = inv_logit_scaled(draws_df_param_recov_b$`bias[1]`), 
                   biasTrue = biasLvl,
                   biasEst = draws_df_param_recov_b$`bias[1]`

                   )
    
    
    if (exists("parameter_recovery_dfb")) {parameter_recovery_dfb <- rbind(parameter_recovery_dfb, temp_paramb)} else {parameter_recovery_dfb <- temp_paramb}
    
  }
```

```{r}
biasS <- ggplot(parameter_recovery_dfb, aes(biasTrue, biasEstScaled)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", color = "orange") +
  xlab("True β")+
  ylab("Estimated β")+
  ggtitle("Parameter Recovery for Bias from the Simple Bayes Model")+
  theme_classic()  

biasS
```


```{r}
# load empirical data
skidata <- read_csv("/Users/kristian/Documents/Skole/8. Semester/Data Science/Exam/DataScienceSkiDecisionMaking/skidata.csv")

# get avi and terrain into probability space (/n+1)
skidata$Source1 <- skidata$AvalancheConditions / 7  # n is 6
skidata$Source2 <- skidata$TerrainCharacteristics / 5 # n is 4

# get sources within scope for working with log-odds (i.e., avoid 0 and 1)
skidata$Source1 <- ifelse(skidata$Source1 == 0, 0.01, 
                  ifelse(skidata$Source1 == 1, 0.99, skidata$Source1))  # i.e., hardcode 0 to be 0.01 and 1 to be 0.99

skidata$Source2 <- ifelse(skidata$Source2 == 0, 0.01, 
                  ifelse(skidata$Source2 == 1, 0.99, skidata$Source2))  # i.e., hardcode 0 to be 0.01 and 1 to be 0.99

```


```{r}
# pivot data wider
sim_wide_skiS <- skidata %>% 
  group_by(id) %>% 
  subset(select = c(id, outcome, Source1, Source2)) %>%
  mutate(row = row_number()) %>% 
  pivot_wider(names_from = id, values_from = c(outcome, Source1, Source2))

# Create the data
dataSimpleBayesSkiS <- list(
  N = nrow(skidata),
  S = unique(skidata$id),
  outcome = as.matrix(sim_wide_skiS[,2:3]),
  Source1 = as.matrix(sim_wide_skiS[,4:5]),
  Source2 = as.matrix(sim_wide_skiS[,6:7])
)

dataSimpleBayesSkiDreS <- sim_wide_skiS %>% 
  subset(select = c(outcome_2, Source1_2, Source2_2)) %>% 
  na.omit()

dataSimpleBayesSkiDreS <- list(
  N = nrow(dataSimpleBayesSkiDreS),
  S = 1,
  outcome = as.matrix(dataSimpleBayesSkiDreS[,1]),
  Source1 = as.matrix(dataSimpleBayesSkiDreS[,2]),
  Source2 = as.matrix(dataSimpleBayesSkiDreS[,3])
)

# feed R the stan model
file <- file.path("simplebayesML.stan")
mod_simpleBayesSkiDreS <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))

   
# create samples from the model
samples_simple_skiDreS <- mod_simpleBayesSkiDreS$sample(
  data = dataSimpleBayesSkiDreS,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500
)

draws_df_ski_DreS <- as_draws_df(samples_simple_skiDreS$draws())
```


```{r}
# Johan
dataSimpleBayesSkiJoeS <- sim_wide_skiS %>% 
  subset(select = c(outcome_1, Source1_1, Source2_1)) %>% 
  na.omit()

dataSimpleBayesSkiJoeS <- list(
  N = nrow(dataSimpleBayesSkiJoeS),
  S = 1,
  outcome = as.matrix(dataSimpleBayesSkiJoeS[,1]),
  Source1 = as.matrix(dataSimpleBayesSkiJoeS[,2]),
  Source2 = as.matrix(dataSimpleBayesSkiJoeS[,3])
)


# feed R the stan model
file <- file.path("simplebayesML.stan")
mod_simpleBayesSkiJoeS <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
   
# create samples from the model
samples_simple_skiJoeS <- mod_simpleBayesSkiJoeS$sample(
  data = dataSimpleBayesSkiJoeS,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500
)

# get the resulting data frame
draws_df_ski_JoeS <- as_draws_df(samples_simple_skiJoeS$draws())
```


```{r}
# basic evaluation
samples_simple_skiJoeS$cmdstan_diagnose()
samples_simple_skiDreS$cmdstan_diagnose()

# diagnostics
summaryJoeS <- samples_simple_skiJoeS$summary()
samples_simple_skiJoeS$loo()

summaryDreS <- samples_simple_skiDreS$summary()
samples_simple_skiDreS$loo()
```

```{r}
# chains mixing plot
p1JoeS <- ggplot(draws_df_ski_JoeS, aes(.iteration, `bias[1]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
p1DreS <- ggplot(draws_df_ski_DreS, aes(.iteration, `bias[1]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
p1JoeS
p1DreS
```



```{r}
# bias plot
DreS <- ggplot(draws_df_ski_DreS) +
  geom_density(aes(`bias_posterior[1]`), alpha = 0.6, fill = "lightblue") +
 # xlim(0,1)+
    annotate("text", colour = "lightblue", x = 0.01, y = 46, label = "Posterior Distribution Bias" , hjust = 0)+
  geom_density(aes(`bias_prior[1]`), alpha = 0.6, fill = "pink") +
    annotate("text", colour = "pink", x = 0.01, y = 43, label = "Prior Distribution Bias", hjust =0)+
  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = mean(db$bias), linetype = "dashed", size = 1.5) +
    annotate("text", x = 0.01, y = 40,  label="Simulated Bias", hjust = 0)+
  geom_vline(xintercept = summaryDreS$q5[60], linetype = "dashed", color = "grey", size = 0.5, alpha = 1)+ # look at this
  geom_vline(xintercept = summaryDreS$q95[60], linetype = "dashed", color = "grey", size = 0.5, alpha = 1)+ # look at this
  geom_rect(aes(xmin = 0, xmax = 0.3, ymin = 38, ymax = 48), 
            fill = "white", color = "black", alpha = 0)


# bias plot
JoeS <- ggplot(draws_df_ski_JoeS) +
  geom_density(aes(`bias_posterior[1]`), alpha = 0.6, fill = "lightblue") +
 # xlim(0,1)+
    annotate("text", colour = "lightblue", x = 0.01, y = 46, label = "Posterior Distribution Bias" , hjust = 0)+
  geom_density(aes(`bias_prior[1]`), alpha = 0.6, fill = "pink") +
    annotate("text", colour = "pink", x = 0.01, y = 43, label = "Prior Distribution Bias", hjust =0)+
  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = mean(db$bias), linetype = "dashed", size = 1.5) +
    annotate("text", x = 0.01, y = 40,  label="Simulated Bias", hjust = 0)+
  geom_vline(xintercept = summaryJoeS$q5[36], linetype = "dashed", color = "grey", size = 0.5, alpha = 1)+
  geom_vline(xintercept = summaryJoeS$q95[36], linetype = "dashed", color = "grey", size = 0.5, alpha = 1)+
  geom_rect(aes(xmin = 0, xmax = 0.3, ymin = 38, ymax = 48), 
            fill = "white", color = "black", alpha = 0)

(DreS|JoeS) + plot_annotation(title = "Prior Posterior Updates for Empirical Data", tag_levels = c("A", "B"), theme = theme(plot.title = element_text(size = 30, hjust = 0.5)))

```