---
title: "Simulating Data"
author: "Kristian Severin"
date: "2023-05-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# loading packages
pacman::p_load(  
  tidyverse,
  brms,
  cmdstanr,
  patchwork,
  future, 
  purrr, 
  furrr
  )

source("SimpleBayes_f.R")  # get self-written simplebayes function from source
source("SimulatingData_f.R")  # get self-written data-simulating function from source
```

Simulating data

```{r}
# set up experimental conditions
nskiers <- 10
ntrials <- 100
bias <- .8
accumulatedAviCond <- c(0,1,2,3,4,5,6)
accumulatedTerrainCond <- c(0,1,2,3,4)

# use self-written function to get simulated data
sim_df <- simulating_skiing(nskiers,ntrials, bias)

```

```{r}
# get sources within scope for working with log-odds (i.e., avoid 0 and 1)
sim_df$Source1 <- ifelse(sim_df$Source1 == 0, 0.01, 
                  ifelse(sim_df$Source1 == 1, 0.99, sim_df$Source1))  # i.e., hardcode 0 to be 0.01 and 1 to be 0.99

sim_df$Source2 <- ifelse(sim_df$Source2 == 0, 0.01, 
                  ifelse(sim_df$Source2 == 1, 0.99, sim_df$Source2))  # i.e., hardcode 0 to be 0.01 and 1 to be 0.99
```

```{r}
# pivot data wider
sim_wide <- sim_df %>% 
  group_by(skier) %>% 
  subset(select = c(skier, outcome, Source1, Source2)) %>%
  mutate(row = row_number()) %>% 
  pivot_wider(names_from = skier, values_from = c(outcome, Source1, Source2))

# Create the data
dataSimpleBayes <- list(
  N = ntrials,
  S = nskiers,
  outcome = as.matrix(sim_wide[,2:11]),
  Source1 = as.matrix(sim_wide[,12:21]),
  Source2 = as.matrix(sim_wide[,22:31])
)

# feed R the stan model
file <- file.path("simplebayesML.stan")
mod_simpleBayes <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
# create samples from the model
samples_simple <- mod_simpleBayes$sample(
  data = dataSimpleBayes,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500
)

# get the resulting data frame
draws_df <- as_draws_df(samples_simple$draws())
```


```{r}
# basic evaluation
samples_simple$cmdstan_diagnose()
# diagnostics
samples_simple$summary()
samples_simple$loo()

```

```{r}
# chains mixing plot
p1 <- ggplot(draws_df, aes(.iteration, `bias[1]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
p2 <- ggplot(draws_df, aes(.iteration, `bias[2]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
p3 <- ggplot(draws_df, aes(.iteration, `bias[3]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
p4 <- ggplot(draws_df, aes(.iteration, `bias[4]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
p5 <- ggplot(draws_df, aes(.iteration, `bias[5]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
p6 <- ggplot(draws_df, aes(.iteration, `bias[6]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
p7 <- ggplot(draws_df, aes(.iteration, `bias[7]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
p8 <- ggplot(draws_df, aes(.iteration, `bias[8]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
p9 <- ggplot(draws_df, aes(.iteration, `bias[9]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
p10 <- ggplot(draws_df, aes(.iteration, `bias[10]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

p_all <- (p1 + p2) + (p3 + p4) + (p5 + 
  p6) + (p7 + p8) + (p9 + p10) + plot_layout(nrow=5, ncol = 2)

p_all

```

```{r}
p_z <- ggplot(draws_df, aes(.iteration, `bias_prior[1]`, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

p_z
```


```{r}
# bias plot
ggplot(draws_df) +
  geom_density(aes(`bias_posterior[1]`), alpha = 0.6, fill = "lightblue") +
    annotate("text", colour = "lightblue", x = 0.01, y = 46, label = "Posterior Distribution Bias" , hjust = 0)+
  geom_density(aes(`bias_prior[1]`), alpha = 0.6, fill = "pink") +
    annotate("text", colour = "pink", x = 0.01, y = 43, label = "Prior Distribution Bias", hjust =0)+
  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = sim_df$bias[1], linetype = "dashed", size = 1.5) +
    annotate("text", x = 0.01, y = 40,  label="True Bias", hjust = 0)+
  geom_rect(aes(xmin = 0, xmax = 0.3, ymin = 38, ymax = 48), 
            fill = "white", color = "black", alpha = 0)

# bias plot
ggplot(draws_df) +
  geom_density(aes(`bias_posterior[2]`), alpha = 0.6, fill = "lightblue") +
    annotate("text", colour = "lightblue", x = 0.01, y = 46, label = "Posterior Distribution Bias" , hjust = 0)+
  geom_density(aes(`bias_prior[2]`), alpha = 0.6, fill = "pink") +
    annotate("text", colour = "pink", x = 0.01, y = 43, label = "Prior Distribution Bias", hjust =0)+
  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = sim_df$bias[1], linetype = "dashed", size = 1.5) +
    annotate("text", x = 0.01, y = 40,  label="True Bias", hjust = 0)+
  geom_rect(aes(xmin = 0, xmax = 0.3, ymin = 38, ymax = 48), 
            fill = "white", color = "black", alpha = 0)

```



```{r}
# prior predictions
ggplot(draws_df) +
  geom_histogram(aes(`prior_preds[1]`), color = "darkblue", fill = "blue", alpha = 0.3) +
  xlab("Predicted skied runs of 1000 trials") +
  ylab("Posterior Density") +
  theme_classic()

# posterior predictions 
ggplot(draws_df) +
  geom_histogram(aes(`posterior_preds[1]`), color = "darkblue", fill = "blue", alpha = 0.3, bins = 90)+
  geom_point(x = sum(sim_df$outcome), y = 0, color = "red", shape = 17, size = 5) +  # not visible
  xlab("Predicted skied runs out of 1000 trials") +
  ylab("Posterior Density") +
  theme_classic()

ggplot(draws_df) +
  geom_histogram(aes(`prior_preds[1]`), color = "lightblue", fill = "blue", alpha = 0.3, bins = 90) +
  geom_histogram(aes(`posterior_preds[1]`), color = "darkblue", fill = "blue", alpha = 0.3, bins = 90) +
  geom_point(x = sum(sim_df$outcome), y = 0, color = "red", shape = 17, size = 5) +
  xlab("Predicted skied runs out of 1000 trials") +
  ylab("Posterior Density") +
  theme_classic()
```
maybe look at this later

```{r}
# A plot of the proportion of right hand choices for the random agents
p1 <- ggplot(sim_df, aes(trial, skier, group = outcome, color = outcome)) + 
  geom_line(alpha = 0.5) + 
  geom_hline(yintercept = 0.5, linetype = "dashed") + 
  ylim(0,1) + 
  theme_classic() 
p1
```




```{r}
# feed R the stan model with priors
file <- file.path("sbPriors.stan")
mod <- cmdstan_model(file, 
                     cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))

# use all cores on the computer
plan(multisession, workers = 4)

# a function that fits different prior values to the simulated data
sim_d_and_fit <- function(prior_mean, prior_sd) {
    
    samples <- mod$sample(
      data = list(
        N = dataSimpleBayes$N,
        S = dataSimpleBayes$S,
        outcome = dataSimpleBayes$outcome,
        Source1 = dataSimpleBayes$Source1,
        Source2 = dataSimpleBayes$Source2,
        prior_mean = prior_mean,
        prior_sd = prior_sd
      ),
      seed = 1000,
      chains = 1,
      parallel_chains = 1,
      threads_per_chain = 1,
      iter_warmup = 1000,
      iter_sampling = 2000,
      refresh = 0,
      max_treedepth = 20,
      adapt_delta = 0.99,
    )
    
    draws_df_sens <- as_draws_df(samples$draws()) 
      temp <- tibble(
                     bias_prior1 = draws_df_sens$`bias_prior[1]`, 
                     bias_posterior1 = draws_df_sens$`bias_posterior[1]`, 
                     prior_preds1 = draws_df_sens$`prior_preds[1]`, 
                     posterior_preds1 = draws_df_sens$`posterior_preds[1]`,
                     
                     bias_prior2 = draws_df_sens$`bias_prior[2]`, 
                     bias_posterior2 = draws_df_sens$`bias_posterior[2]`, 
                     prior_preds2 = draws_df_sens$`prior_preds[2]`, 
                     posterior_preds2 = draws_df_sens$`posterior_preds[2]`,
                     
                     bias_prior3 = draws_df_sens$`bias_prior[3]`, 
                     bias_posterior3 = draws_df_sens$`bias_posterior[3]`, 
                     prior_preds3 = draws_df_sens$`prior_preds[3]`, 
                     posterior_preds3 = draws_df_sens$`posterior_preds[3]`,
                     
                     bias_prior4 = draws_df_sens$`bias_prior[4]`, 
                     bias_posterior4 = draws_df_sens$`bias_posterior[4]`, 
                     prior_preds4 = draws_df_sens$`prior_preds[4]`, 
                     posterior_preds4 = draws_df_sens$`posterior_preds[4]`,
                     
                     bias_prior5 = draws_df_sens$`bias_prior[5]`, 
                     bias_posterior5 = draws_df_sens$`bias_posterior[5]`, 
                     prior_preds5 = draws_df_sens$`prior_preds[5]`, 
                     posterior_preds5 = draws_df_sens$`posterior_preds[5]`,
                     
                     bias_prior6 = draws_df_sens$`bias_prior[6]`, 
                     bias_posterior6 = draws_df_sens$`bias_posterior[6]`, 
                     prior_preds6 = draws_df_sens$`prior_preds[6]`, 
                     posterior_preds6 = draws_df_sens$`posterior_preds[6]`,
                     
                     bias_prior7 = draws_df_sens$`bias_prior[7]`, 
                     bias_posterior7 = draws_df_sens$`bias_posterior[7]`, 
                     prior_preds7 = draws_df_sens$`prior_preds[7]`, 
                     posterior_preds7 = draws_df_sens$`posterior_preds[7]`,
                     
                     bias_prior8 = draws_df_sens$`bias_prior[8]`, 
                     bias_posterior8 = draws_df_sens$`bias_posterior[8]`, 
                     prior_preds8 = draws_df_sens$`prior_preds[8]`, 
                     posterior_preds8 = draws_df_sens$`posterior_preds[8]`,
                     
                     bias_prior9 = draws_df_sens$`bias_prior[9]`, 
                     bias_posterior9 = draws_df_sens$`bias_posterior[9]`, 
                     prior_preds9 = draws_df_sens$`prior_preds[9]`, 
                     posterior_preds9 = draws_df_sens$`posterior_preds[9]`,
                     
                     bias_prior10 = draws_df_sens$`bias_prior[10]`, 
                     bias_posterior10 = draws_df_sens$`bias_posterior[10]`, 
                     prior_preds10 = draws_df_sens$`prior_preds[10]`, 
                     posterior_preds10 = draws_df_sens$`posterior_preds[10]`,
                     
                     prior_mean = prior_mean,
                     prior_sd = prior_sd,
                     
                     
                     )
    
    return(temp)
  
}



# calling function self-written function that simulates data and fits it by sequences of different priors
recovery_df <- future_pmap_dfr(priors, sim_d_and_fit, .options = furrr_options(seed = TRUE))

```

```{r}
# recovery
ggplot(recovery_df, aes(prior_mean, bias_posterior1)) +
  geom_point(alpha = 0.1) +
  geom_hline(yintercept = 0.8, color = "red") +
  geom_smooth() +
  facet_wrap(.~prior_sd) +
  theme_classic()

ggplot(recovery_df, aes(prior_mean, bias_posterior2)) +
  geom_point(alpha = 0.1) +
  geom_hline(yintercept = 0.8, color = "red") +
  geom_smooth() +
  facet_wrap(.~prior_sd) +
  theme_classic()


```


```{r}
ggplot(sim_df, aes(sim_df$temp_a)) +
  geom_histogram(bins = 10, alpha = 0.3, color = "black") +
  theme_bw()
```

```{r}
ggplot(sim_df, aes(Source1, temp_a, color = Source2, group = Source2)) +
  geom_line() +
  theme_bw()
```
```{r}
ggplot(sim_df, aes(outcome)) +
  geom_histogram(bins = 10, alpha = 0.3, color = "black") +
  theme_bw()
```

```{r}
ggplot(sim_df, aes(Source2, outcome, color = Source1, group = Source1)) +
  geom_smooth(se = F) +
  theme_bw()

ggplot(sim_df, aes(sim_df$a)) +
  geom_histogram(bins = 10, alpha = 0.3, color = "black") +
  theme_bw()
```

```{r}
ggplot(sim_df, aes(Source1, a, color = Source2, group = Source2)) +
  geom_smooth() +
  theme_bw()
```

