---
title: "Simulating Data"
author: "Kristian Severin"
date: "2023-05-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# loading packages
pacman::p_load(  
  tidyverse,
  brms,
  cmdstanr,
  patchwork
  )

source("SimpleBayes_f.R")  # get self-written simplebayes function from source
```

Simulating data

```{r}
# set up experimental conditions
ntrials <- 110
nskiers <- 10
bias <- .7
accumulatedAviCond <- c(0,1,2,3,4,5,6)
accumulatedTerrainCond <- c(0,1,2,3,4)





df <- NULL
simulating_skiing <- function(nskier, nskiers, bias, accumulatedAviCond, accumulatedTerrainCond){

# saving information
Source1 <- array(NA, ntrials)
Source2 <- array(NA, ntrials)
decision <- array(NA, ntrials)
assessmentAvi <- array(NA, ntrials)
assessmentTerrain <- array(NA, ntrials)
temp_a <- array(NA, ntrials)  # temporary overall assessment
a <- array(NA, ntrials) # overall assessment
outcome <- array(NA, ntrials) # did they ski

for (skier in 1:nskiers){
  for (i in 1:ntrials){
    # create random assessment for avi conditions
    assessmentAvi[i] <- sample(accumulatedAviCond, 1, replace = TRUE)
    # make assessment for avi cond on 0-1 space (divide with n+1)
    Source1[i] <- assessmentAvi[i] / 8
    # create random assessment for terrain conditions
    assessmentTerrain[i] <- sample(accumulatedTerrainCond, 1, replace = TRUE)
    # make assessment for terrain cond on 0-1 space (divide with n+1)
    Source2[i] <- assessmentTerrain[i] / 6
    # get temporay overall assessment
    temp_a[i] <- SimpleBayes_f(bias, Source1[i], Source2[i])
  
  
    # this nested ifelse gets an overall assessment on a normal scale
    a[i] <- ifelse(round(temp_a[i]*11,0) < 0, 0,  # a can be an integer from 0-10 
            ifelse(round(temp_a[i]*11,0) > 10, 10, round(temp_a[i]*11,0)))
    # this nested ifelse gets the outcome. Did the person ski or not
    outcome[i] <- ifelse(a[i] >= 8, 0, 
                  ifelse(a[i] <= 4, 1, rbinom(1, 1, .5))) # all integers between 4 and 8 are computed as 50/50 

  }
    
    # get everything in a tibble 
    temp_df <- tibble(skier = seq(nskiers), trial = seq(ntrials), bias, assessmentAvi, assessmentTerrain, Source1, Source2,temp_a,     a, outcome)
    
    if (exists("df")) { df <- rbind(df, temp_df)} else{df <- temp_df}
    
  }
 
  return(df)
}

sim_df <- simulating_skiing(nskiers, ntrials, bias, accumulatedAviCond, accumulatedTerrainCond)

```

```{r}
# get sources within scope
sim_df$Source1 <- ifelse(sim_df$Source1 == 0, 0.01, 
                  ifelse(sim_df$Source1 == 1, 0.99, sim_df$Source1))  # i.e., hardcode 0 to be 0.01 and 1 to be 0.99

sim_df$Source2 <- ifelse(sim_df$Source2 == 0, 0.01, 
                  ifelse(sim_df$Source2 == 1, 0.99, sim_df$Source2))  # i.e., hardcode 0 to be 0.01 and 1 to be 0.99
```

```{r}
# trying to add different priors to bias
prior_mean <- seq(0, 1, 0.1)
prior_sd <- seq(0.1, 1, 0.1)
priors <-  expand.grid(prior_mean, prior_sd)
priors <- tibble(prior_mean = priors$Var1, prior_sd = priors$Var2)

sim_df <- cbind(sim_df, priors)
```


```{r}
# prepare data for stan - simple bayes
data_simpleBayes <- list(
  N = nrow(sim_df),
  outcome = sim_df$outcome, # the outcome (did they ski or not)
  Source1 = sim_df$Source1, # own rating on 0-1 space
  Source2 = sim_df$Source2, # group raing on 0-1 space
  prior_mean = sim_df$prior_mean,
  prior_sd = sim_df$prior_sd
)
# feed R the stan model
file <- file.path("hej.stan")
mod_simpleBayes <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
samples_simple <- mod_simpleBayes$sample(
  data = data_simpleBayes,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500
)
# basic evaluation
samples_simple$cmdstan_diagnose()
```

```{r}
# diagnostics
samples_simple$summary()
samples_simple$loo()
draws_df <- as_draws_df(samples_simple$draws())
ggplot(draws_df, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
ggplot(draws_df) +
  geom_density(aes(bias), alpha = 0.6, fill = "lightblue") +
  geom_density(aes(bias_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = sim_df$bias[1]) +
  theme_bw()
```



