---
title: "preprocessing"
author: "Kristian Severin"
date: "2023-05-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages
pacman::p_load(tidyverse)
```

```{r}
# load data
dataJoe <- readxl::read_xlsx("DataJohan.xlsx")
dataDre <- readxl::read_xlsx("DataAndreas.xlsx")

# add id
dataJoe <- dataJoe %>% 
  mutate(id = 1)

# add id
dataDre <- dataDre %>% 
  mutate(id = 2)

# merge
skidata <- rbind(dataJoe, dataDre)

# rename stuff 
skidata <- skidata %>% rename("AvalancheConditions" = "Avi Conditions (opdaterer automatisk)")
skidata <- skidata %>% rename("TerrainCharacteristics" = "Terrain Characteristics (opdaterer automatisk)")
skidata <- skidata %>% rename("TripLevel" = "Trip Planner Level of Caution (done at home)")
skidata <- skidata %>% rename("outcome" = "To ski or not to ski")

# if value then
skidata$outcome <- ifelse(skidata$outcome == "Ski", 1, 
                   ifelse(skidata$outcome == "Not to ski", 0, skidata$outcome))

write_csv(skidata, "/Users/kristian/Documents/Skole/8. Semester/Data Science/Exam/DataScienceSkiDecisionMaking/skidata.csv")

```

