---
title: "Simulating Data"
author: "Kristian Severin"
date: "2023-05-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# loading packages
pacman::p_load(  
  tidyverse,
  brms,
  cmdstanr,
  patchwork
  )

source("SimpleBayes_f.R")  # get self-written simplebayes function from source
source("SimulatingData_f.R")  # get self-written data-simulating function from source
```

Simulating data

```{r}
# set up experimental conditions
nskiers <- 10
ntrials <- 100
bias <- .8
accumulatedAviCond <- c(0,1,2,3,4,5,6)
accumulatedTerrainCond <- c(0,1,2,3,4)

sim_df <- simulating_skiing(nskiers,ntrials, bias)

```

```{r}
# get sources within scope
sim_df$Source1 <- ifelse(sim_df$Source1 == 0, 0.01, 
                  ifelse(sim_df$Source1 == 1, 0.99, sim_df$Source1))  # i.e., hardcode 0 to be 0.01 and 1 to be 0.99

sim_df$Source2 <- ifelse(sim_df$Source2 == 0, 0.01, 
                  ifelse(sim_df$Source2 == 1, 0.99, sim_df$Source2))  # i.e., hardcode 0 to be 0.01 and 1 to be 0.99
```

```{r}
# trying to add different priors to bias
prior_mean <- seq(0, 1, 0.1)
prior_sd <- seq(0.1, 1, 0.01)
priors <-  expand.grid(prior_mean, prior_sd)
priors <- tibble(prior_mean = priors$Var1, prior_sd = priors$Var2)

priors <- priors[-1001,]


sim_df <- cbind(sim_df, priors)
```


```{r}
for (s in 1:nskiers){
  df_temp <- sim_df %>% 
    filter(skier == s)

# prepare data for stan - simple bayes
data_simpleBayes <- list(
  N = nrow(sim_df),
  skiers = sim_df$skier,
  outcome = sim_df$outcome, # the outcome (did they ski or not)
  Source1 = sim_df$Source1, # own rating on 0-1 space
  Source2 = sim_df$Source2 # group rating on 0-1 space
#  prior_mean = priors$prior_mean,
#  prior_sd = priors$prior_sd
)
# feed R the stan model
file <- file.path("simplebayes.stan")
mod_simpleBayes <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
samples_simple <- mod_simpleBayes$sample(
  data = data_simpleBayes,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500
)

  temp <- as_draws_df(samples_simple$draws())
  temp <- temp %>% 
    mutate(skier = s)
  

  if (exists("draws_df_emp")) { draws_df_emp <- rbind(draws_df_emp, temp)} 
  else{draws_df_emp <- temp} 
}
```

```{r}
# basic evaluation
samples_simple$cmdstan_diagnose()
# diagnostics
samples_simple$summary()
samples_simple$loo()
# chains mixing plot
draws_df <- as_draws_df(samples_simple$draws())
ggplot(draws_df, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

# bias plot
ggplot(draws_df) +
  geom_density(aes(bias_posterior), alpha = 0.6, fill = "lightblue") +
    annotate("text", colour = "lightblue", x = 0.01, y = 46, label = "Posterior Distribution Bias" , hjust = 0)+
  geom_density(aes(bias_prior), alpha = 0.6, fill = "pink") +
    annotate("text", colour = "pink", x = 0.01, y = 43, label = "Prior Distribution Bias", hjust =0)+
  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  geom_vline(xintercept = sim_df$bias[1], linetype = "dashed", size = 1.5) +
    annotate("text", x = 0.01, y = 40,  label="True Bias", hjust = 0)+
  geom_rect(aes(xmin = 0, xmax = 0.3, ymin = 38, ymax = 48), 
            fill = "white", color = "black", alpha = 0)
```

multilevel 
```{r}
# chains mixing plot

ggplot(draws_df_emp, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

# bias plot
ggplot(draws_df_emp) +
  geom_density(aes(bias_posterior), alpha = 0.6, fill = "lightblue") +
    annotate("text", colour = "lightblue", x = 0.01, y = 46, label = "Posterior Distribution Bias" , hjust = 0)+
  geom_density(aes(bias_prior), alpha = 0.6, fill = "pink") +
    annotate("text", colour = "pink", x = 0.01, y = 43, label = "Prior Distribution Bias", hjust =0)+
  xlab("Bias")+
  ylab("Estimate Densitites")+
  theme_bw()+
  facet_wrap(.~skier) +
  geom_vline(xintercept = sim_df$bias[1], linetype = "dashed", size = 1.5) +
    annotate("text", x = 0.01, y = 40,  label="True Bias", hjust = 0)+
  geom_rect(aes(xmin = 0, xmax = 0.3, ymin = 38, ymax = 48), 
            fill = "white", color = "black", alpha = 0)

```








```{r}
ggplot(draws_df) +
  geom_histogram(aes(prior_preds), color = "darkblue", fill = "blue", alpha = 0.3) +
  xlab("Predicted skied runs of 100 trials") +
  ylab("Posterior Density") +
  theme_classic()
```

```{r}
# A plot of the proportion of right hand choices for the random agents
p1 <- ggplot(sim_df, aes(trial, skier, group = outcome, color = outcome)) + 
  geom_line(alpha = 0.5) + 
  geom_hline(yintercept = 0.5, linetype = "dashed") + 
  ylim(0,1) + 
  theme_classic() 
p1
```


